### ISSUE TITLE
PHP Fatal error:  Call to undefined method Piwik\\IP::N2P() in Ip2Hostname.php on line 55

### ISSUE THREAD

**Issue by ping0xFF** [ThaDafinser/Piwik-Ip2Hostname#2]
I'm getting the error:

PHP Fatal error:  Call to undefined method Piwik\IP::N2P() in /home/me/mysite/public/piwik/plugins/Ip2Hostname/Columns/Ip2Hostname.php on line 55

I'm using Piwik 2.14.3

**Comment by ThaDafinser** [comment]
@sybind sorry forget to create a release: https://github.com/ThaDafinser/Piwik-Ip2Hostname/releases/tag/1.0.3

It was already fixed some time ago...
