### ISSUE TITLE
Update plugin.json required version

### ISSUE THREAD

**Issue by tsteur** [ThaDafinser/Piwik-Ip2Hostname#4]
Hi @ThaDafinser ,

We recently made some changes on the Marketplace and changed how versions are defined. In your plugin.json it defines:

``` json
  "require": {
    "piwik": "2.15.0",
    "php": "5.5.0"
  }
```

but in future updates it should include the `>=` and also include an upper version constraint:

``` json
  "require": {
    "piwik": ">=2.15.0,<3.0.0-b1",
    "php": ">=5.5.0"
  }
```

Sorry for inconvenience and cheers

**Comment by ThaDafinser** [comment]
@tsteur are all "composer like" version constraints allowed? Like `^2.15.0` or `~2.15.0`

https://getcomposer.org/doc/articles/versions.md

**Comment by tsteur** [comment]
Not yet. The Marketplace already can handle it as we are using composer for this but it's not in the Piwik app itself yet. I will work on this and even bring support for this into Piwik 2.X. It should be in Piwik 2.16.3 or 2.16.4 in a few weeks

**Comment by tsteur** [comment]
It may be better though to use it only for 3.X plugins as older Piwik versions won't be able to understand this definition and then maybe decide to disable this plugin. This is something I will need to test in the next weeks.

**Comment by ThaDafinser** [comment]
implemented
https://github.com/ThaDafinser/Piwik-Ip2Hostname/releases/tag/v2.1.0
